version: '3.4'

services:
  ui:
    image: ui
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    networks:
      - unabnetwork

networks:
  unabnetwork:
    name: unabnetwork
    driver: bridge
  orionsoft:
    name: orionsoft
    driver: bridge